use_frameworks!

target 'LPYBase_Example' do
  pod 'LPYBase', :path => '../'

  target 'LPYBase_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
